services:
  flask_db:
    image: postgres
    container_name: flask_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGUSER=postgres
    shm_size: 128mb
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 
    mem_limit: 512m
    mem_reservation: 128M
    memswap_limit: 1g
    cpus: "0.5"
    cpuset: "1"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_app:
    container_name: flask-app
    build: 
      context: .
      dockerfile: /Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app/
    depends_on:
      flask_db:
        condition: service_healthy
    environment:
      - PROPERTYMANAGER_ENV=dev
      - DATABASE_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    mem_limit: 512m
    mem_reservation: 128M
    memswap_limit: 1g
    cpus: "0.5"
    cpuset: "1"

volumes:
  pgdata: {}