services:

  flask_db:
    image: postgres
    container_name: flask_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGUSER=postgres
    shm_size: 128mb
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 
    mem_limit: 512m
    mem_reservation: 128M
    memswap_limit: 1g
    cpus: "0.5"
    cpuset: "1"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  flask_app:
    container_name: flask-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: debugger # only for dev
      #target: primary # for prod
    ports:
       - 5000:5000
       - 5678:5678 # only for dev
    volumes:
      - .:/app/
    depends_on:
      flask_db:
        condition: service_healthy
    environment:
      - PROPERTYMANAGER_ENV=dev
      - DATABASE_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    mem_limit: 512m
    mem_reservation: 128M
    memswap_limit: 1g
    cpus: "0.5"
    cpuset: "1"


  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5050:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
     - smtp4dev-data:/smtp4dev
    environment:
    - ServerOptions__Urls=http://*:80
    - ServerOptions__HostName=smtp4dev
    mem_limit: 512m
    mem_reservation: 128M
    memswap_limit: 1g
    cpus: "0.5"
    cpuset: "1"



volumes:
  pgdata: {}
  smtp4dev-data: