"""Adding Tenants and Notes models

Revision ID: 019ded45b389
Revises: 2f64e22c275f
Create Date: 2020-07-15 15:41:11.962226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019ded45b389'
down_revision = '2f64e22c275f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('tenancy_start_date', sa.Date(), nullable=False),
    sa.Column('tenancy_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name=op.f('fk_tenant_property_id_property')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant'))
    )
    op.create_table('tenantNote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenantNote_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenantNote'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenantNote')
    op.drop_table('tenant')
    # ### end Alembic commands ###
