"""empty message

Revision ID: 2ab43c9c7bd4
Revises: 75816fc7c6b0
Create Date: 2024-10-11 17:15:21.780799

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2ab43c9c7bd4'
down_revision = '75816fc7c6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
