"""removing owner_id from property

Revision ID: 3ef4bab79677
Revises: 3aaa34ca9623
Create Date: 2023-12-23 21:11:05.452609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef4bab79677'
down_revision = '3aaa34ca9623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint('fk_property_owner_id_user', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_property_owner_id_user', 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
