"""empty message

Revision ID: 3fa97ce707f3
Revises: fd6dc92d51b3
Create Date: 2024-09-17 17:58:12.298513

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3fa97ce707f3'
down_revision = 'fd6dc92d51b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)

    with op.batch_alter_table('tenant-document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tenant-document_document_type_id_document-type'), 'document-type', ['document_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant-document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tenant-document_document_type_id_document-type'), type_='foreignkey')
        batch_op.drop_column('document_type_id')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
