"""sorting floats out on property model

Revision ID: 5205c78ea76f
Revises: bafde7051ea0
Create Date: 2024-09-11 18:17:43.618103

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5205c78ea76f'
down_revision = 'bafde7051ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(precision=10),
               existing_nullable=True)
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(precision=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
