"""Added created and updated dates to models

Revision ID: 6970dbd9388e
Revises: e565d498bcbd
Create Date: 2022-04-21 10:59:24.627068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6970dbd9388e'
down_revision = 'e565d498bcbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_on')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_on')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tenantNote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('tenantNote', schema=None) as batch_op:
        batch_op.drop_column('updated_date')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
