"""extending tenant doc model

Revision ID: 75816fc7c6b0
Revises: 3fa97ce707f3
Create Date: 2024-09-17 18:22:26.760681

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '75816fc7c6b0'
down_revision = '3fa97ce707f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)

    with op.batch_alter_table('tenant-document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_ext', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant-document', schema=None) as batch_op:
        batch_op.drop_column('file_ext')
        batch_op.drop_column('file_name')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
