"""added created_on to property

Revision ID: 88d5af0bdba1
Revises: 522ddc85027c
Create Date: 2020-06-15 12:56:26.279186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d5af0bdba1'
down_revision = '522ddc85027c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('address_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'property', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###
