"""moving the rest of the models oveer to mapped_column

Revision ID: 909aed147f89
Revises: 919cedb909f4
Create Date: 2025-02-24 21:05:18.218824

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '909aed147f89'
down_revision = '919cedb909f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('line_1',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('post_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)

    with op.batch_alter_table('propertyImages', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('propertyImages', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('monthly_rental_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('post_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('line_1',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
