"""Added Title to tenant and Owner props to property

Revision ID: a9ba158a41e4
Revises: ccd2aba4a234
Create Date: 2020-08-03 12:19:55.442476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ba158a41e4'
down_revision = 'ccd2aba4a234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_property_owner_id_user'), 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_property_owner_id_user'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
