"""moving tenant image to base64 str in new table

Revision ID: a9f85dc67a8e
Revises: 6970dbd9388e
Create Date: 2022-04-25 15:13:33.548562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f85dc67a8e'
down_revision = '6970dbd9388e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant-profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant-profile_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant-profile'))
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('tenant-profile')
    # ### end Alembic commands ###
