"""email type on tenant

Revision ID: bafde7051ea0
Revises: d8a8abc97714
Create Date: 2024-09-11 17:56:33.085497

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "bafde7051ea0"
down_revision = "d8a8abc97714"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenant", schema=None) as batch_op:
        batch_op.alter_column(
            "email_address",
            existing_type=sa.VARCHAR(length=100),
            type_=sqlalchemy_utils.types.email.EmailType(length=255),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenant", schema=None) as batch_op:
        batch_op.alter_column(
            "email_address",
            existing_type=sqlalchemy_utils.types.email.EmailType(length=255),
            type_=sa.VARCHAR(length=100),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
