"""Adding sold_date to property

Revision ID: c4903ec87ea9
Revises: 09de7956da10
Create Date: 2023-07-06 16:31:04.183810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4903ec87ea9'
down_revision = '09de7956da10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('sold_date')

    # ### end Alembic commands ###
