"""empty message

Revision ID: fb78f1b780b7
Revises: 502647777858
Create Date: 2023-08-11 22:19:31.986360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb78f1b780b7'
down_revision = '502647777858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_public_id', type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_public_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.create_unique_constraint('uq_user_public_id', ['public_id'])
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###
